### ISSUE TITLE
Undefined symbol error with VectorizationBase 0.14.12 on Julia 1.5.2

### ISSUE THREAD

**Issue by mmiller-max** [JuliaLang/PackageCompiler.jl#487] opened 2021-01-07 09:22 UTC
This may be similar to #445  and #456 but this is occurring for me in Julia 1.5.2 if a project or project dependency uses VectorizationBase v0.14.12. The same projects are fine with v0.13.12

## MWE
Building this package:
```Julia
module TestPkg

using VectorizationBase

greet() = print("Hello World!")

end # module
```
With this `Project.toml`:
```toml
name = "TestPkg"
uuid = "5e43b693-7ccd-488e-962a-6f83670885ee"
version = "0.1.0"

[deps]
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
VectorizationBase = "3d5dd08c-fd9d-11e8-17fa-ed2836048c2f"

[compat]
VectorizationBase = "0.13.12"
```
Builds successfully with
```Julia
create_sysimage([:TestPkg]; sysimage_path="TestPkg.so")
```
Changing `Project.toml` to:
```toml
name = "TestPkg"
uuid = "5e43b693-7ccd-488e-962a-6f83670885ee"
version = "0.1.0"

[deps]
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
VectorizationBase = "3d5dd08c-fd9d-11e8-17fa-ed2836048c2f"

[compat]
VectorizationBase = "0.14.12"
```
Results in this error:
```Julia
julia> create_sysimage([:TestPkg2]; sysimage_path="TestPkg2.so")
[ Info: PackageCompiler: creating system image object file, this might take a while...
Undefined symbols for architecture x86_64:
  "_jfptr_llvmcall_expr_72687", referenced from:
      _tojlinvoke76774 in jl_qVNoRE.o(text.o)
  "_jfptr_llvmname_72469", referenced from:
      _tojlinvoke76801 in jl_qVNoRE.o(text.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ERROR: failed process: Process(`gcc -m64 -march=x86-64 -shared -L/Applications/Julia-1.5.app/Contents/Resources/julia/lib -o TestPkg2.so -Wl,-all_load /var/folders/29/f6ksj93n5dz5zwdbz89rt9kh95rtb6/T/jl_qVNoRE.o -ljulia`, ProcessExited(1)) [1]

Stacktrace:
 [1] pipeline_error at ./process.jl:525 [inlined]
 [2] run(::Cmd; wait::Bool) at ./process.jl:440
 [3] run at ./process.jl:438 [inlined]
 [4] run_with_env at /Users/malmiller/.julia/packages/PackageCompiler/KeZOk/src/PackageCompiler.jl:101 [inlined]
 [5] create_sysimg_from_object_file(::String, ::String) at /Users/malmiller/.julia/packages/PackageCompiler/KeZOk/src/PackageCompiler.jl:497
 [6] create_sysimage(::Array{Symbol,1}; sysimage_path::String, project::String, precompile_execution_file::Array{String,1}, precompile_statements_file::Array{String,1}, incremental::Bool, filter_stdlibs::Bool, replace_default::Bool, cpu_target::String, script::Nothing, base_sysimage::Nothing, isapp::Bool) at /Users/malmiller/.julia/packages/PackageCompiler/KeZOk/src/PackageCompiler.jl:451
 [7] top-level scope at REPL[11]:1
```

## Context that may help
I found this issues when working with a larger package that uses `DiffEqBase`. In that case, the sys image build successfully (possibly because it was in a Docker Julia v1.5 container) but when loading I got a similar error to #445. Comparing the manifests between a previous working version of this package I found the `VectorizationBase` version change was the culprit.

## Versioninfo
```
julia> versioninfo()
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 8
```

**Comment by DilumAluthge** [comment] 2021-01-08 04:11
cc: @chriselrod

**Comment by chriselrod** [comment] 2021-01-08 04:51
I guess git bisect is the best way to find out what's going wrong?

**Comment by chriselrod** [comment] 2021-01-08 05:54
Oddly, I can reproduce when I've added a version of VectorizationBase, but not when it is `dev`ed.

**Comment by DilumAluthge** [comment] 2021-01-08 05:56
You can write a script manually to iterate over commit shas. And then do `Pkg.add(Pkg.PackageSpec(name = "VectorizationBase", rev = COMMIT_SHA))`.

**Comment by chriselrod** [comment] 2021-01-08 05:59
Is there a convenient way to get a vector of commit shas?

**Comment by chriselrod** [comment] 2021-01-08 06:43
Maybe I'm doing something wrong, but it keeps working, snapshot of script output:
```julia
  Resolving package versions...
Updating `~/Documents/progwork/julia/env/pkgcompiler_vecbase/TestPkg/Project.toml`
  [3d5dd08c] ~ VectorizationBase v0.14.13 `https://github.com/chriselrod/VectorizationBase.jl.git#95c1994` ⇒ v0.14.12 `https://github.com/chriselrod/VectorizationBase.jl.git#b4a3479`
Updating `~/Documents/progwork/julia/env/pkgcompiler_vecbase/TestPkg/Manifest.toml`
  [3d5dd08c] ~ VectorizationBase v0.14.13 `https://github.com/chriselrod/VectorizationBase.jl.git#95c1994` ⇒ v0.14.12 `https://github.com/chriselrod/VectorizationBase.jl.git#b4a3479`
sha = "b4a3479fde575824836d06b4a7b1ee5cff9925d1"
Project TestPkg v0.1.0
Status `~/Documents/progwork/julia/env/pkgcompiler_vecbase/TestPkg/Project.toml`
  [9b87118b] PackageCompiler v1.2.4
  [3d5dd08c] VectorizationBase v0.14.12 `https://github.com/chriselrod/VectorizationBase.jl.git#b4a3479`
[ Info: PackageCompiler: creating system image object file, this might take a while...
succeeded = true
```
That is the commit of the 0.14.12 release:
https://github.com/chriselrod/VectorizationBase.jl/commit/b4a3479fde575824836d06b4a7b1ee5cff9925d1

**Comment by chriselrod** [comment] 2021-01-08 06:48
Maybe without having `compat` restrict to a specific VectorizationBase version, PkgCompiler ignores the package's environment?

**Comment by chriselrod** [comment] 2021-01-08 06:54
Anyway, the stack trace you the OP shared:
```julia
julia> create_sysimage([:TestPkg2]; sysimage_path="TestPkg2.so")
[ Info: PackageCompiler: creating system image object file, this might take a while...
Undefined symbols for architecture x86_64:
  "_jfptr_llvmcall_expr_72687", referenced from:
      _tojlinvoke76774 in jl_qVNoRE.o(text.o)
  "_jfptr_llvmname_72469", referenced from:
      _tojlinvoke76801 in jl_qVNoRE.o(text.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ERROR: failed process: Process(`gcc -m64 -march=x86-64 -shared -L/Applications/Julia-1.5.app/Contents/Resources/julia/lib -o TestPkg2.so -Wl,-all_load /var/folders/29/f6ksj93n5dz5zwdbz89rt9kh95rtb6/T/jl_qVNoRE.o -ljulia`, ProcessExited(1)) [1]

Stacktrace:
 [1] pipeline_error at ./process.jl:525 [inlined]
 [2] run(::Cmd; wait::Bool) at ./process.jl:440
 [3] run at ./process.jl:438 [inlined]
 [4] run_with_env at /Users/malmiller/.julia/packages/PackageCompiler/KeZOk/src/PackageCompiler.jl:101 [inlined]
 [5] create_sysimg_from_object_file(::String, ::String) at /Users/malmiller/.julia/packages/PackageCompiler/KeZOk/src/PackageCompiler.jl:497
 [6] create_sysimage(::Array{Symbol,1}; sysimage_path::String, project::String, precompile_execution_file::Array{String,1}, precompile_statements_file::Array{String,1}, incremental::Bool, filter_stdlibs::Bool, replace_default::Bool, cpu_target::String, script::Nothing, base_sysimage::Nothing, isapp::Bool) at /Users/malmiller/.julia/packages/PackageCompiler/KeZOk/src/PackageCompiler.jl:451
 [7] top-level scope at REPL[11]:1
```
Mentions `llvmname`, which is defined as:
```julia
function llvmname(op, WR, WA, T, TA)
    lret = LLVM_TYPES[T]
    ln = "llvm.$op.$(suffix(WR,T))"
    (isone(abs(WR)) || T !== first(TA)) ? ln * '.' * suffix(maximum(WA),first(TA)) : ln
end
```
`LLVM_TYPES` is:
```julia
struct Bit; data::Bool; end # Dummy for Ptr
const NativeTypesExceptBit = Union{Bool,HWReal}
const NativeTypes = Union{NativeTypesExceptBit, Bit}
const LLVM_TYPES = IdDict{Type{<:NativeTypes},String}(
    Float32 => "float",
    Float64 => "double",
    Int8 => "i8",
    Int16 => "i16",
    Int32 => "i32",
    Int64 => "i64",
    UInt8 => "i8",
    UInt16 => "i16",
    UInt32 => "i32",
    UInt64 => "i64",
    Bool => "i8",
    Bit => "i1"
)
```
Could the `IdDict` be causing problems?
I'm grasping at straws here.

**Comment by DilumAluthge** [comment] 2021-01-08 06:58
@mmiller-max Can you reproduce the error on the latest Julia nightly or the latest Julia master?

**Comment by chriselrod** [comment] 2021-01-08 07:06
FWIW, I was using Julia 1.5.3 above.

**Comment by mmiller-max** [comment] 2021-01-08 07:08
@DilumAluthge will give it a go

**Comment by mmiller-max** [comment] 2021-01-08 07:31
Whilst that's running, @chriselrod does your script remove the `Manifest.toml`? When I was trying to reproduce I had to manually delete it, setting `compat` to 0.14 didn't update the manifest if it already at 0.13 in it.

**Comment by chriselrod** [comment] 2021-01-08 07:37
I didn't remove the `Manifest.toml`, and I set the `[compat]` to
```toml
[compat]
VectorizationBase = "0.13, 0.14"
```
And my `Manifest.toml` does seem to be updating, e.g. it currently says:
```toml
[[VectorizationBase]]
deps = ["ArrayInterface", "Hwloc", "IfElse", "Libdl", "LinearAlgebra"]
git-tree-sha1 = "51adc974cea83f935a34526b15c552edf39cfae8"
repo-rev = "2abed879a356bd1a2e9129a66ddcdfabe68b9708"
repo-url = "https://github.com/chriselrod/VectorizationBase.jl.git"
uuid = "3d5dd08c-fd9d-11e8-17fa-ed2836048c2f"
version = "0.14.6"
```
while my script says
```julia
  Resolving package versions...
Updating `~/Documents/progwork/julia/env/pkgcompiler_vecbase/TestPkg/Project.toml`
  [3d5dd08c] ~ VectorizationBase v0.14.6 `https://github.com/chriselrod/VectorizationBase.jl.git#2d793a7` ⇒ v0.14.6 `https://github.com/chriselrod/VectorizationBase.jl.git#2abed87`
Updating `~/Documents/progwork/julia/env/pkgcompiler_vecbase/TestPkg/Manifest.toml`
  [3d5dd08c] ~ VectorizationBase v0.14.6 `https://github.com/chriselrod/VectorizationBase.jl.git#2d793a7` ⇒ v0.14.6 `https://github.com/chriselrod/VectorizationBase.jl.git#2abed87`
sha = "2abed879a356bd1a2e9129a66ddcdfabe68b9708"
Project TestPkg v0.1.0
Status `~/Documents/progwork/julia/env/pkgcompiler_vecbase/TestPkg/Project.toml`
  [9b87118b] PackageCompiler v1.2.4
  [3d5dd08c] VectorizationBase v0.14.6 `https://github.com/chriselrod/VectorizationBase.jl.git#2abed87`
[ Info: PackageCompiler: creating system image object file, this might take a while...
```
The `2abed87` matches.

**Comment by mmiller-max** [comment] 2021-01-08 07:40
Hmm, I get a similar error on latest master:
```julia
[ Info: PackageCompiler: creating system image object file, this might take a while...
Undefined symbols for architecture x86_64:
  "_jsysw_llvmname_170", referenced from:
      _tojlinvoke54137 in jl_bYDbWe.o(text.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ERROR: failed process: Process(`gcc -m64 -march=x86-64 -shared -L/Users/malmiller/repos/julia/usr/lib -L/Users/malmiller/repos/julia/usr/lib -o TestPkg.so -Wl,-all_load /var/folders/29/f6ksj93n5dz5zwdbz89rt9kh95rtb6/T/jl_bYDbWe.o -ljulia-internal -ljulia`, ProcessExited(1)) [1]

Stacktrace:
 [1] pipeline_error
   @ ./process.jl:525 [inlined]
 [2] run(::Cmd; wait::Bool)
   @ Base ./process.jl:440
 [3] run
   @ ./process.jl:438 [inlined]
 [4] run_with_env
   @ ~/.julia/packages/PackageCompiler/KeZOk/src/PackageCompiler.jl:101 [inlined]
 [5] create_sysimg_from_object_file(input_object::String, sysimage_path::String)
   @ PackageCompiler ~/.julia/packages/PackageCompiler/KeZOk/src/PackageCompiler.jl:497
 [6] create_sysimage(packages::Vector{Symbol}; sysimage_path::String, project::String, precompile_execution_file::Vector{String}, precompile_statements_file::Vector{String}, incremental::Bool, filter_stdlibs::Bool, replace_default::Bool, cpu_target::String, script::Nothing, base_sysimage::Nothing, isapp::Bool)
   @ PackageCompiler ~/.julia/packages/PackageCompiler/KeZOk/src/PackageCompiler.jl:451
 [7] top-level scope
   @ REPL[9]:1
```

```Julia
julia> versioninfo()
Julia Version 1.7.0-DEV.236
Commit 83bee67631 (2021-01-08 02:28 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, skylake)
Environment:
  OR_JULIA_REGISTRY_SSH_DIR = /Users/malmiller/.ssh/registry_id_rsa
  JULIA_NUM_THREADS = 8
```

**Comment by chriselrod** [comment] 2021-01-08 07:43
Odd. And `llvmname` came up again: `"_jsysw_llvmname_170"`

**Comment by mmiller-max** [comment] 2021-01-08 08:26
0.14.6 worked for me too (on 1.5.3)

**Comment by mmiller-max** [comment] 2021-01-08 08:42
With some more testing, everything up to 0.14.11 is fine too

**Comment by DilumAluthge** [comment] 2021-01-08 08:43
Presumably then the problem is somewhere in here:

https://github.com/chriselrod/VectorizationBase.jl/compare/v0.14.11...v0.14.12

**Comment by chriselrod** [comment] 2021-01-08 08:49
My first guess would be that it's the diff in `precompile` (and that `llvmname` actually doesn't have anything to do with it).

**Comment by KristofferC** [comment] 2021-01-08 09:30
> If so, is there any way I can detect if the code is being run by PackageCompiler?

Not really because package compiler just uses the precompiled files from a normal julia session.

**Comment by chriselrod** [comment] 2021-01-08 09:48
@mmiller-max, could you check if that precompile statement is to blame (i.e., dev the library and comment it out)?
If it is, because I can't detect PackageCompiler is running the code, I'll have to avoid such statements (which is unfortunate, because inference time was moderately high for it).

If it's something else, then I still don't know what the problem is.

**Comment by chriselrod** [comment] 2021-01-08 09:49
I'm not sure what happened earlier when I did say I got an error, but I cannot reproduce this issue at all (even with 0.14.12).

**Comment by mmiller-max** [comment] 2021-01-08 10:26
@chriselrod yep sure I'll give commenting that out a test, will have to be tomorrow though. Thanks for looking into this so quickly today

**Comment by chriselrod** [comment] 2021-01-08 11:02
Great, thanks for helping track the problem down!

**Comment by mmiller-max** [comment] 2021-01-09 04:42
As you suspected @chriselrod it's this line that causes the problem:

https://github.com/chriselrod/VectorizationBase.jl/blob/37cc93559e0689416062c00f38ce250c36e3977b/src/precompile.jl#L13

When commented out the sysimage builds successfully.

Another way I was able to reproduce it by was just by building a sysimage with just `VectorizationBase`:

```Julia
# From /path/to/VectorizationBase.jl, commit 6c15e62288e41754db90328a82e38338405dd3c6
(VectorizationBase) pkg>add PackageCompiler
julia> create_sysimage([:VectorizationBase]; sysimage_path="VectorizationBase.so")
Undefined symbols for architecture x86_64:
  "_jfptr_llvmcall_expr_67028", referenced from:
      _tojlinvoke71686 in jl_EjMi4u.o(text.o)
  "_jfptr_llvmname_66763", referenced from:
      _tojlinvoke71713 in jl_EjMi4u.o(text.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ERROR: failed process: Process(`gcc -m64 -march=x86-64 -shared -L/Applications/Julia-1.5.app/Contents/Resources/julia/lib -o VectorizationBase.so -Wl,-all_load /var/folders/29/f6ksj93n5dz5zwdbz89rt9kh95rtb6/T/jl_EjMi4u.o -ljulia`, ProcessExited(1)) [1]

Stacktrace:
 [1] pipeline_error at ./process.jl:525 [inlined]
 [2] run(::Cmd; wait::Bool) at ./process.jl:440
 [3] run at ./process.jl:438 [inlined]
 [4] run_with_env at /Users/malmiller/.julia/packages/PackageCompiler/KeZOk/src/PackageCompiler.jl:101 [inlined]
 [5] create_sysimg_from_object_file(::String, ::String) at /Users/malmiller/.julia/packages/PackageCompiler/KeZOk/src/PackageCompiler.jl:497
 [6] create_sysimage(::Array{Symbol,1}; sysimage_path::String, project::String, precompile_execution_file::Array{String,1}, precompile_statements_file::Array{String,1}, incremental::Bool, filter_stdlibs::Bool, replace_default::Bool, cpu_target::String, script::Nothing, base_sysimage::Nothing, isapp::Bool) at /Users/malmiller/.julia/packages/PackageCompiler/KeZOk/src/PackageCompiler.jl:451
 [7] top-level scope at REPL[5]:1
```

Hopefully this method works for you.

**Comment by chriselrod** [comment] 2021-01-09 10:34
What happens if you
```
create_sysimage([:VectorizationBase]; sysimage_path="VectorizationBase.so", cpu_target = "native")
```
?

**Comment by mmiller-max** [comment] 2021-01-10 22:54
> `create_sysimage([:VectorizationBase]; sysimage_path="VectorizationBase.so", cpu_target = "native")`

I get the same error with this.

Interestingly, if I use the following dockerfile:
```dockerfile
FROM julia:1.5.3

RUN apt-get update && apt-get install -y gcc

WORKDIR /app

COPY . .

RUN julia --project=. -e 'using Pkg; Pkg.add("PackageCompiler"); using PackageCompiler; create_sysimage([:VectorizationBase]; sysimage_path="VectorizationBase.so")'

ENTRYPOINT ["julia", "-JVectorizationBase.so", "-e", "println(\"Started\")"]
```
The  sysimage builds in the docker contianer fine, but the sysimage fails to load:
```cmd
$ docker build -t vectorisation-base -t
...
$ docker run vectorization-base
ERROR: could not load library "/app/VectorizationBase.so"
/app/VectorizationBase.so: undefined symbol: jfptr_llvmname_27369
```

**Comment by ranocha** [comment] 2021-01-21 14:28
I get the same error using Julia v1.5.3 on Ubuntu with an Intel i7-8700K.
```julia
using Pkg, Libdl
Pkg.activate(temp=true)
Pkg.add("PackageCompiler")
packages = [:VectorizationBase]
map(Pkg.add ∘ string, packages)
Pkg.precompile()
using PackageCompiler
PackageCompiler.create_sysimage(
  packages,
  sysimage_path="custom_sysimage." * Libdl.dlext,
  cpu_target="native"
)
```
works, but 
```
julia --sysimage=custom_sysimage.so
ERROR: could not load library ".../custom_sysimage.so"
.../custom_sysimage.so: undefined symbol: jfptr_llvmname_27801
Segmentation fault (core dumped)
```

**Comment by chriselrod** [comment] 2021-01-21 20:09
```julia
> julia -q --project=.              (base)
julia> using Pkg, Libdl

julia> Pkg.activate(temp=true)
  Activating new environment at `/tmp/jl_6shiOA/Project.toml`

julia> exit()
chriselrod@clr-7b12d38c3bf247448c96becf747df83f ~/D/p/j/e/pkgcompiler_vecbase> /home/chriselrod/Documents/languages/julia/usr/bin/julia -q                          (base)
julia> using Pkg, Libdl

julia> Pkg.activate(temp=true)
  Activating new environment at `/tmp/jl_yw3fft/Project.toml`

julia> packages = [:VectorizationBase];

julia> map(Pkg.add ∘ string, packages);
    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
    Updating `/tmp/jl_yw3fft/Project.toml`
  [3d5dd08c] + VectorizationBase v0.15.5
    Updating `/tmp/jl_yw3fft/Manifest.toml`
  [4fba245c] + ArrayInterface v2.14.14
  [0e44f5e4] + Hwloc v1.2.0
  [615f187c] + IfElse v0.1.0
  [692b3bcd] + JLLWrappers v1.2.0
  [ae029012] + Requires v1.1.2
  [3d5dd08c] + VectorizationBase v0.15.5
  [e33a78d0] + Hwloc_jll v2.4.0+0
  [0dad84c5] + ArgTools
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [f43a241f] + Downloads
  [b77e0a4c] + InteractiveUtils
  [b27032c2] + LibCURL
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [ca575930] + NetworkOptions
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [2f01184e] + SparseArrays
  [fa267f1f] + TOML
  [a4e569a6] + Tar
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
  [deac9b47] + LibCURL_jll
  [29816b5a] + LibSSH2_jll
  [c8ffd9c3] + MbedTLS_jll
  [14a3606d] + MozillaCACerts_jll
  [83775a58] + Zlib_jll
  [8e850ede] + nghttp2_jll

julia> Pkg.precompile()

julia> using PackageCompiler

julia> PackageCompiler.create_sysimage(
         packages,
         sysimage_path="custom_sysimage." * Libdl.dlext,
         cpu_target="native"
       )
[ Info: PackageCompiler: creating system image object file, this might take a while...

julia> exit()
> julia -q --sysimage=custom_sysimage.so
julia> 1+2
3

julia> @time using VectorizationBase
  0.000091 seconds (1.03 k allocations: 76.703 KiB, 2450.97% compilation time)
```
Still can't reproduce. =/

**Comment by ranocha** [comment] 2021-01-22 02:56
Thanks for the feedback! I can confirm that it works for me if I use the latest Julia nightly build (Version 1.7.0-DEV.358 (2021-01-21), Commit a40335766e*).

**Comment by chriselrod** [comment] 2021-01-22 05:58
Okay, I'll try 1.5 or 1.6.
If the problem is the precompute statements, good news is that it sounds like I should be able to turn them back on in Julia >= 1.7.

**Comment by chriselrod** [comment] 2021-01-22 08:25
I could reproduce with Julia 1.5. Should be fixed in the latest release (VectorizationBase 0.15.7).

**Comment by ranocha** [comment] 2021-01-22 08:48
I can confirm that everything works for me using VectorizationBase v0.15.7. Thanks for the quick fix, @chriselrod :+1:

**Closed** 2021-01-22 09:08 UTC

**Comment by mmiller-max** [comment] 2021-01-22 10:59
Cheers @chriselrod !
