### ISSUE TITLE
Fails to compile DataFrames.jl package

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaLang/PackageCompiler.jl#199] opened 2019-03-04 10:03 UTC
I am on Windows 10 Pro and I installed the latest DataFrames.jl package v0.17.1 and I am using v0.6.3 of PackageCompiler.jl.

when I do `compile_package("DataFrames", force = false)` I get the below message. I am not sure what this means, so I tried `using Pkg` and the do `compile_package("DataFrames", force = false)` again, then it says 

> > using PackageCompiler; compile_package("DataFrames", force = false)
> [ Info: Registered package DataFrames, using already given UUID: a93c6f00-e57d-5684-b7b6-d8193f3e46c0
> 

Is this some kind of error?

**Original Error**
> [ Info: used 9206 out of 9207 precompile statements
> Julia program file:
>   "C:\Users\RTX2080\.julia\packages\PackageCompiler\oT98U\sysimg\precompile.jl"
> Build directory:
>   "C:\Users\RTX2080\.julia\packages\PackageCompiler\oT98U\sysimg"
> ┌ Info: Something went wrong
> │   err = ArgumentError("Package Pkg not found in current path:\n- Run `import Pkg; Pkg.add(\"Pkg\")` to install the Pkg package.\n")
> └ @ Main C:\Users\RTX2080\.julia\config\startup.jl:21
> ┌ Info: activating new environment at C:\Users\RTX2080\.julia\packages\PackageCompiler\oT98U\packages\Project.toml.
> └ @ Pkg.API C:\Users\RTX2080\AppData\Local\Julia-1.1.0\share\julia\stdlib\v1.1\Pkg\src\API.jl:519
>   Updating registry at `C:\Users\RTX2080\.julia\registries\General`
>   Updating git-repo `https://github.com/JuliaRegistries/General.git`
> fatal: error thrown and no exception handler available.
> ErrorException("Task cannot be serialized")
> rec_backtrace at /home/Administrator/buildbot/worker/package_win64/build/src\stackwalk.c:94
> record_backtrace at /home/Administrator/buildbot/worker/package_win64/build/src\task.c:217 [inlined]
> jl_throw at /home/Administrator/buildbot/worker/package_win64/build/src\task.c:417
> jl_error at /home/Administrator/buildbot/worker/package_win64/build/src\rtutils.c:41
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:294
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:252 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:286
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:252 [inlined]
> jl_serialize_module at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:230 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:291
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:915 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:303
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:915 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:303
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:915 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:303
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:252 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:277
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:915 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:303
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:252 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:277
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:915 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:303
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:915 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:303
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:915 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:303
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:915 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:303
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:915 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:303
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:915 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:303
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:915 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:303
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:915 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:303
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:252 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:268
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:252 [inlined]
> jl_serialize_module at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:230 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:291
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:252 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:286
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:915 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:303
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:915 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:303
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:915 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:303
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:915 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:303
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:915 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:303
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:915 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:303
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:915 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:303
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:915 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:303
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:252 [inlined]
> jl_serialize_module at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:230 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:291
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:252 [inlined]
> jl_serialize_module at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:230 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:291
> jl_serialize_module at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:222 [inlined]
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:291
> jl_serialize_value_ at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:337 [inlined]
> jl_save_system_image_to_stream at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:1273
> jl_create_system_image at /home/Administrator/buildbot/worker/package_win64/build/src\staticdata.c:1378
> jl_write_compiler_output at /home/Administrator/buildbot/worker/package_win64/build/src\precompile.c:76
> jl_atexit_hook at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\init.c:222
> wmain at /home/Administrator/buildbot/worker/package_win64/build/ui\repl.c:218
> __tmainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-5.0.3-1/crt\crtexe.c:329
> mainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-5.0.3-1/crt\crtexe.c:212
> BaseThreadInitThunk at C:\Windows\System32\KERNEL32.DLL (unknown line)
> RtlUserThreadStart at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
> ERROR: failed process: Process(`'C:\Users\RTX2080\AppData\Local\Julia-1.1.0\bin\julia.exe' '--sysimage=C:\Users\RTX2080\.julia\packages\PackageCompiler\oT98U\sysimg\backup\native\sys.dll' --output-o=sys.a --track-allocation=none --code-coverage=none --history-file=yes '--trace-compile=C:\Users\RTX2080\.julia\packages\Fezzik\OIt3R\traces\trace_4065806587.jl' --inline=yes --math-mode=ieee --compile=yes --track-allocation=none --sysimage-native-code=yes '--sysimage=C:\Users\RTX2080\AppData\Local\Julia-1.1.0\lib\julia\sys.dll' --compiled-modules=yes --optimize=2 'C:\Users\RTX2080\.julia\packages\PackageCompiler\oT98U\sysimg\run_julia_code.jl'`, ProcessExited(1)) [1]
> Stacktrace:
>  [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at .\error.jl:42
>  [2] pipeline_error at .\process.jl:785 [inlined]
>  [3] #run#515(::Bool, ::Function, ::Cmd) at .\process.jl:726
>  [4] run at .\process.jl:724 [inlined]
>  [5] #run_julia#1 at C:\Users\RTX2080\.julia\packages\PackageCompiler\oT98U\src\compiler_flags.jl:225 [inlined]
>  [6] #run_julia at .\none:0 [inlined]
>  [7] (::getfield(PackageCompiler, Symbol("##13#14")){Base.Iterators.Pairs{Symbol,Any,NTuple{14,Symbol},NamedTuple{(:sysimage, :startup_file, :handle_signals, :sysimage_native_code, :compiled_modules, :depwarn, :warn_overwrite, :compile, :cpu_target, :optimize, :debug_level, :inline, :check_bounds, :math_mode),Tuple{String,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing}}},String})() at C:\Users\RTX2080\.julia\packages\PackageCompiler\oT98U\src\static_julia.jl:262
>  [8] cd(::getfield(PackageCompiler, Symbol("##13#14")){Base.Iterators.Pairs{Symbol,Any,NTuple{14,Symbol},NamedTuple{(:sysimage, :startup_file, :handle_signals, :sysimage_native_code, :compiled_modules, :depwarn, :warn_overwrite, :compile, :cpu_target, :optimize, :debug_level, :inline, :check_bounds, :math_mode),Tuple{String,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing}}},String}, ::String) at .\file.jl:85
>  [9] #build_object#12(::Base.Iterators.Pairs{Symbol,Any,NTuple{14,Symbol},NamedTuple{(:sysimage, :startup_file, :handle_signals, :sysimage_native_code, :compiled_modules, :depwarn, :warn_overwrite, :compile, :cpu_target, :optimize, :debug_level, :inline, :check_bounds, :math_mode),Tuple{String,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing}}}, ::Function, ::String, ::String, ::String, ::Bool) at C:\Users\RTX2080\.julia\packages\PackageCompiler\oT98U\src\static_julia.jl:261
>  [10] #build_object at .\none:0 [inlined]
>  [11] build_object(::String, ::String, ::String, ::Bool, ::String, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing) at C:\Users\RTX2080\.julia\packages\PackageCompiler\oT98U\src\static_julia.jl:240
>  [12] #static_julia#5(::Nothing, ::Bool, ::Bool, ::String, ::String, ::Nothing, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Nothing, ::Bool, ::Bool, ::String, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::typeof(static_julia), ::String) at C:\Users\RTX2080\.julia\packages\PackageCompiler\oT98U\src\static_julia.jl:161
>  [13] #static_julia at .\none:0 [inlined]
>  [14] #build_sysimg#29(::Bool, ::Bool, ::Bool, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::Nothing, ::typeof(PackageCompiler.build_sysimg), ::String, ::String) at C:\Users\RTX2080\.julia\packages\PackageCompiler\oT98U\src\api.jl:25
>  [15] #build_sysimg at .\none:0 [inlined]
>  [16] #compile_package#67(::Bool, ::Bool, ::Bool, ::Nothing, ::Bool, ::Function, ::Tuple{String,String}) at C:\Users\RTX2080\.julia\packages\PackageCompiler\oT98U\src\PackageCompiler.jl:130
>  [17] #compile_package#64 at .\none:0 [inlined]
>  [18] (::getfield(PackageCompiler, Symbol("#kw##compile_package")))(::NamedTuple{(:force,),Tuple{Bool}}, ::typeof(compile_package), ::String) at .\none:0
>  [19] top-level scope at none:0

**Comment by pfitzseb** [comment] 2019-03-06 10:53
Looks like a duplicate of https://github.com/JuliaLang/PackageCompiler.jl/issues/184. Can you try again with `pkg> dev PackageCompiler`?

**Comment by xiaodaigh** [comment] 2019-03-18 11:02
Ok fixed with latest DEv

**Comment by xiaodaigh** [comment] 2019-06-27 10:44
Can not compile :DataFrames on windows with v0.6.4+. Used to have no problems

**Comment by KristofferC** [comment] 2020-02-11 08:02
Should work now.

**Closed by KristofferC** 2020-02-11 08:02 UTC
