### ISSUE TITLE
Crash when creating sysimage

### ISSUE THREAD

**Issue by brianguenter** [JuliaLang/PackageCompiler.jl#809] opened 2023-05-11 17:24 UTC
Installed julia with juliaup.

To reproduce fork https://github.com/brianguenter/FastSymbolicDifferentiation.jl. Open subproject FSDBenchmarks in VSCode and run Task -> build task in VSCode to build the sysimage.

<details>
   <summary> Version info </summary>

```
julia> versioninfo()
Julia Version 1.9.0
Commit 8e63055292 (2023-05-07 11:25 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 32 × AMD Ryzen 9 7950X 16-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, znver3)
  Threads: 32 on 32 virtual cores
Environment:
  JULIA_EDITOR = code.cmd
```
</details>

<details>
   <summary> Error message </summary>

``` Activating project at `c:\Users\seatt\.vscode\extensions\julialang.language-julia-1.38.2\scripts\environments\sysimagecompile\fallback`
[ Info: Now building a custom sysimage for the environment 'c:\Users\seatt\source\FastSymbolicDifferentiation\FSDBenchmark', excluding dev packages '[:FastSymbolicDifferentiation]'.
┌ Info: Included packages: 
│       - CSV
│       - Rsvg
│       - Statistics
│       - Memoize
│       - BenchmarkTools
│       - Interpolations
│       - TimerOutputs
│       - HTTP
│       - Symbolics
│       - LinearAlgebra
│       - LaTeXStrings
│       - SparseArrays
│       - Plots
│       - FileIO
│       - StaticArrays
│       - DifferentialEquations
│       - Cairo
│       - CurveFit
│       - DataFrames
└       - Rotations
[ Info: Precompile statement files: String[]
[ Info: Precompile execution files: String[]
⢰ [00m:23s] PackageCompiler: compiling incremental system image
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x0 -- unknown function (ip: 0000000000000000)
in expression starting at C:\Users\seatt\.julia\packages\Polynomials\XRaIT\src\precompiles.jl:4
unknown function (ip: 0000000000000000)
Allocations: 30521122 (Pool: 30501433; Big: 19689); GC: 41
⣠ [00m:24s] PackageCompiler: compiling incremental system image
ERROR: LoadError: failed process: Process(`'C:\Users\seatt\.julia\juliaup\julia-1.9.0+0.x64.w64.mingw32\bin\julia.exe' --color=yes --startup-file=no --cpu-target=native -O3 '--sysimage=C:\Users\seatt\.julia\juliaup\julia-1.9.0+0.x64.w64.mingw32\lib\julia\sys.dll' '--project=c:\Users\seatt\source\FastSymbolicDifferentiation\FSDBenchmark' '--output-o=C:\Users\seatt\AppData\Local\Temp\jl_Habw1CnWpM.o' 'C:\Users\seatt\AppData\Local\Temp\jl_B07obUVubq'`, ProcessExited(1)) [1]

Stacktrace:
  [1] pipeline_error
    @ .\process.jl:565 [inlined]
  [2] run(::Cmd; wait::Bool)
    @ Base .\process.jl:480
  [3] run
    @ .\process.jl:477 [inlined]
  [4] #14
    @ c:\Users\seatt\.vscode\extensions\julialang.language-julia-1.38.2\scripts\packages\PackageCompiler\ext\TerminalSpinners.jl:157 [inlined]
  [5] spin(f::PackageCompiler.var"#14#15"{Cmd}, s::PackageCompiler.TerminalSpinners.Spinner{Base.TTY})
    @ PackageCompiler.TerminalSpinners c:\Users\seatt\.vscode\extensions\julialang.language-julia-1.38.2\scripts\packages\PackageCompiler\ext\TerminalSpinners.jl:164
  [6] macro expansion
    @ c:\Users\seatt\.vscode\extensions\julialang.language-julia-1.38.2\scripts\packages\PackageCompiler\ext\TerminalSpinners.jl:157 [inlined]
  [7] create_sysimg_object_file(object_file::String, packages::Vector{String}, packages_sysimg::Set{Base.PkgId}; project::String, base_sysimage::String, precompile_execution_file::Vector{String}, precompile_statements_file::Vector{String}, cpu_target::String, script::Nothing, sysimage_build_args::Cmd, extra_precompiles::String, incremental::Bool)
    @ PackageCompiler c:\Users\seatt\.vscode\extensions\julialang.language-julia-1.38.2\scripts\packages\PackageCompiler\src\PackageCompiler.jl:359
  [8] create_sysimg_object_file
    @ c:\Users\seatt\.vscode\extensions\julialang.language-julia-1.38.2\scripts\packages\PackageCompiler\src\PackageCompiler.jl:244 [inlined]
  [9] create_sysimage(packages::Vector{Symbol}; sysimage_path::String, project::String, precompile_execution_file::Vector{String}, precompile_statements_file::Vector{String}, incremental::Bool, filter_stdlibs::Bool, cpu_target::String, script::Nothing, sysimage_build_args::Cmd, include_transitive_dependencies::Bool, base_sysimage::Nothing, julia_init_c_file::Nothing, version::Nothing, soname::Nothing, compat_level::String, extra_precompiles::String)
    @ PackageCompiler c:\Users\seatt\.vscode\extensions\julialang.language-julia-1.38.2\scripts\packages\PackageCompiler\src\PackageCompiler.jl:510
 [10] top-level scope
    @ c:\Users\seatt\.vscode\extensions\julialang.language-julia-1.38.2\scripts\tasks\task_compileenv.jl:94
in expression starting at c:\Users\seatt\.vscode\extensions\julialang.language-julia-1.38.2\scripts\tasks\task_compileenv.jl:94<!--
```
</details>
If you have a question please search or post to our Discourse site: https://discourse.julialang.org.
We use the GitHub issue tracker for bug reports and feature requests only.

If you're submitting a bug report, be sure to include as much relevant information as
possible, including:

1. The output of `versioninfo()`
2. How you installed Julia
3. A minimal working example (MWE), also known as a minimum reproducible example

If you're experiencing a problem with a particular package, open an issue on that
package's repository instead.

Thanks for contributing to the Julia project!
-->

**Comment by DilumAluthge** [comment] 2024-10-18 02:43
The repo linked in the issue no longer exists, so there is no way for someone to try to reproduce the bug.

So I'll close this issue as "can't reproduce", but if the OP is able to post the steps to reproduce, then I can re-open this issue.

**Closed by DilumAluthge** 2024-10-18 02:43 UTC
